[2022-09-11T16:22:02.266+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: scrapping_etl.etl manual__2022-09-11T16:22:00.756643+00:00 [queued]>
[2022-09-11T16:22:02.277+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: scrapping_etl.etl manual__2022-09-11T16:22:00.756643+00:00 [queued]>
[2022-09-11T16:22:02.278+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-11T16:22:02.280+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-11T16:22:02.282+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-11T16:22:02.293+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): etl> on 2022-09-11 16:22:00.756643+00:00
[2022-09-11T16:22:02.306+0000] {standard_task_runner.py:52} INFO - Started process 22558 to run task
[2022-09-11T16:22:02.310+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scrapping_etl', 'etl', 'manual__2022-09-11T16:22:00.756643+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/job_dag.py', '--cfg-path', '/tmp/tmp150vydm1', '--error-file', '/tmp/tmpeqr2ak5j']
[2022-09-11T16:22:02.314+0000] {standard_task_runner.py:80} INFO - Job 11: Subtask etl
[2022-09-11T16:22:02.466+0000] {task_command.py:371} INFO - Running <TaskInstance: scrapping_etl.etl manual__2022-09-11T16:22:00.756643+00:00 [running]> on host 71464bd58847
[2022-09-11T16:22:02.545+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=c.mendozar@outlook.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrapping_etl
AIRFLOW_CTX_TASK_ID=etl
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T16:22:00.756643+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-11T16:22:00.756643+00:00
[2022-09-11T16:22:06.226+0000] {logging_mixin.py:115} INFO - 2022-09-11
[2022-09-11T16:22:06.229+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 20, in etl_jobs
    print('datetime:', datetime.datetime(day))
TypeError: an integer is required (got type str)
[2022-09-11T16:22:06.243+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=scrapping_etl, task_id=etl, execution_date=20220911T162200, start_date=20220911T162202, end_date=20220911T162206
[2022-09-11T16:22:06.252+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task etl (an integer is required (got type str); 22558)
[2022-09-11T16:22:06.301+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-11T16:22:06.342+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
